In [1]:
import pandas

In [2]:
import pathlib

In [3]:
import numpy
import glob

In [9]:
fl = "/Users/simondi/PROJECTS/target_infect_x_project/src/tix-analysis/data/kmeans-transformed-recursive-clusters/"

In [10]:
files = [x for x in glob.glob(fl + "*") if x.endswith(".csv")]

In [11]:
files

['/Users/simondi/PROJECTS/target_infect_x_project/src/tix-analysis/data/kmeans-transformed-recursive-clusters/part-00005-b3b3403d-8398-45b2-bfad-f5d1e3f53877-c000.csv',
 '/Users/simondi/PROJECTS/target_infect_x_project/src/tix-analysis/data/kmeans-transformed-recursive-clusters/part-00004-b3b3403d-8398-45b2-bfad-f5d1e3f53877-c000.csv',
 '/Users/simondi/PROJECTS/target_infect_x_project/src/tix-analysis/data/kmeans-transformed-recursive-clusters/part-00008-b3b3403d-8398-45b2-bfad-f5d1e3f53877-c000.csv',
 '/Users/simondi/PROJECTS/target_infect_x_project/src/tix-analysis/data/kmeans-transformed-recursive-clusters/part-00007-b3b3403d-8398-45b2-bfad-f5d1e3f53877-c000.csv',
 '/Users/simondi/PROJECTS/target_infect_x_project/src/tix-analysis/data/kmeans-transformed-recursive-clusters/part-00006-b3b3403d-8398-45b2-bfad-f5d1e3f53877-c000.csv',
 '/Users/simondi/PROJECTS/target_infect_x_project/src/tix-analysis/data/kmeans-transformed-recursive-clusters/part-00001-b3b3403d-8398-45b2-bfad-f5d1e3f538

In [45]:
files[0]

'/Users/simondi/PROJECTS/target_infect_x_project/src/tix-analysis/data/kmeans-transformed-recursive-clusters-parquet/part-00005-b3b3403d-8398-45b2-bfad-f5d1e3f53877-c000.csv'

In [26]:
 df = pandas.reddad_csv(files[0], sep="\t", nrows=1000)

In [58]:
df[df.prediction == 1]

Empty DataFrame
Columns: [study, pathogen, library, design, replicate, plate, well, gene, sirna, well_type, image_idx, object_idx, prediction, f_0, f_1, f_2, f_3, f_4, f_5, f_6, f_7, f_8, f_9, f_10, f_11, f_12, f_13, f_14]
Index: []

[0 rows x 28 columns]

In [13]:
s = pandas.read_csv(files[0], sep="\t", nrows=1000, usecols=lambda x: x.startswith("f_"))

In [19]:
s

f_0       f_1       f_2       f_3       f_4       f_5       f_6  \
0 -1.377171  0.600481  0.282947 -0.435507 -0.895857  0.549325  0.156719   
1 -1.549955  0.345142  0.611393  0.146361 -0.629563  0.346930  0.158055   
2 -2.324351 -0.013947  0.915348  0.933641 -0.134705  1.321229  0.265913   
3 -0.232403 -0.084361 -0.234863  0.699538 -0.437137  1.653184  0.093481   

        f_7       f_8       f_9      f_10      f_11      f_12      f_13  \
0 -0.533515 -0.160561  0.047071 -0.577789  0.047928  0.725588 -0.399858   
1 -1.388385  0.167901  0.966286  0.556068  0.130966  0.411240 -0.531940   
2 -3.302936  0.120706  2.034551  0.428786 -0.405558  1.132213 -0.191257   
3 -1.396315  0.110718  0.016090 -0.017684  0.666631 -0.010084  0.230484   

       f_14  
0  0.909398  
1  1.121847  
2  1.088962  
3  0.154581

In [17]:
import scipy.spatial

In [25]:
k = scipy.spatial.distance.cdist(s.iloc[:2], s)

In [26]:
k

array([[0.        , 1.94703469, 4.23026082, 2.79153451],
       [1.94703469, 0.        , 2.89767811, 2.81190408]])

In [31]:
d = scipy.mean(k, axis=1)

In [28]:
d

array([2.2422075 , 1.91415422])

In [29]:
scipy.vstack([d,d]).T

array([[2.2422075 , 2.2422075 ],
       [1.91415422, 1.91415422]])

In [48]:
df = None

In [49]:
for fl in files:
    df2 = pandas.read_csv(fl, sep="\t", nrows=1000, usecols=lambda x: x.startswith("f_") or x.startswith("pred"))
    df = pandas.concat([df, df2])

In [71]:
df[df.prediction == 0]

prediction       f_0       f_1       f_2       f_3       f_4       f_5  \
0            0  0.983076  0.400526  0.059323  0.891297  0.645930 -1.640774   
1            0 -0.433314  0.484706  0.199532  0.515719 -0.070778  0.353788   
2            0  1.383970 -1.317822  0.123975  0.043758 -0.134047  0.088680   
3            0 -0.285577 -0.956465 -0.070795  0.126882 -0.339024  0.431682   
4            0  0.505887 -0.772248 -0.196128 -0.698482 -0.977952  0.291180   
5            0  0.139040 -1.022992  0.222662 -0.820219 -0.403342  0.502229   
6            0 -1.125896 -0.699048 -0.411038 -1.049683 -0.963801  0.112087   
7            0  0.804139 -0.926409 -0.021752 -0.530349 -1.049957 -1.744346   
8            0 -0.682317 -0.235497  0.245066  2.008464  0.343213 -2.057680   
9            0 -0.665714  0.236016 -0.115199 -0.065868 -0.299639 -1.338271   
10           0 -0.495503  0.862675  0.324341  0.454615  0.481537 -0.123256   
11           0  1.045096 -0.947156  0.468234  0.828913  0.958826  0.084605   
12           0  0.514910 -0.633485  0.348839  0.893543 -0.409540 -0.339176   
13           0 -0.217590 -0.260587  0.480708 -0.369192 -0.261390  0.416872   
14           0  0.418795 -1.719195  0.645626  0.233274 -0.030954  0.112246   
15           0 -0.655393 -0.404798  0.039023  0.119391 -0.641459 -0.134895   
16           0 -0.007632 -1.168786 -0.354808  0.796618 -0.411340  0.520898   
17           0  0.397568 -1.495616  0.427256  0.929493 -0.921097  0.269159   
18           0 -0.257103 -0.517592 -0.047676  1.208477 -0.124120  0.436017   

         f_6       f_7       f_8       f_9      f_10      f_11      f_12  \
0   0.077990  0.696373  0.204197 -0.640538 -1.268777 -0.502997  0.463260   
1  -0.052812  1.454771  0.345548 -0.522970 -0.090074  1.126331 -0.357611   
2   0.136664  0.328222  0.521857  0.281087 -0.659636 -0.707708 -0.419449   
3  -0.036466  1.844441  0.592229 -0.500280 -0.829114  0.744380 -0.841767   
4  -0.058590  2.112324  0.451552 -0.903070 -0.721684  0.635161 -0.652323   
5   0.043780  0.443958  0.250788 -0.441662 -0.966644  0.416846 -0.335546   
6  -0.111715  1.445988  0.255013 -0.598836 -0.871914  0.562513 -0.172921   
7  -0.208293  2.299100  0.846013 -1.233939 -1.159164  1.340370 -0.346796   
8   0.009135  0.438135  1.079477  0.778933 -0.225972 -0.029768 -0.047482   
9   0.045442  0.786776  0.575027 -0.188427 -0.406317 -0.027128 -0.453692   
10  0.068876  1.088613 -0.370118 -0.622589 -0.972481 -0.138049  0.176741   
11 -0.055913  0.650364  0.092480 -0.171037 -1.288269  0.214831  0.346466   
12  0.231314 -0.072762  0.786842  0.552776 -0.352649 -0.499139 -0.468411   
13 -0.010705  1.154040 -0.429741 -0.331582 -1.060740  0.016367  0.009960   
14  0.074086  2.150335  0.568516 -0.499903 -2.048509  0.150464 -0.682668   
15  0.163801  0.622690  0.864650  0.124070 -0.267612  0.261542 -1.024135   
16 -0.008246  1.437170  0.759766 -0.497068 -1.196831  0.315475 -0.608466   
17  0.030016  1.531800  0.972211 -0.105255 -1.069748  0.914471 -1.078133   
18 -0.009999  0.580722  1.018441  0.121967  0.612558  1.227803 -1.453968   

        f_13      f_14  
0  -1.330727 -0.447457  
1  -1.137713  0.127587  
2  -0.507346  0.279108  
3  -1.671612  0.685388  
4  -0.708185  0.315887  
5  -0.534507  0.266648  
6  -0.737253  0.569262  
7  -1.132954 -1.021399  
8  -2.584598  0.428047  
9  -1.158913 -0.142867  
10 -1.100818  0.488087  
11 -0.624445 -0.601672  
12 -1.530816  0.829322  
13 -0.065271  0.475074  
14 -2.423329  0.986267  
15 -1.895585  0.958691  
16 -1.383337  0.316042  
17 -1.917575  0.643592  
18 -1.869009  0.639531

In [76]:
df[df.prediction == 0].iloc[:, 1:]

f_0       f_1       f_2       f_3       f_4       f_5       f_6  \
0   0.983076  0.400526  0.059323  0.891297  0.645930 -1.640774  0.077990   
1  -0.433314  0.484706  0.199532  0.515719 -0.070778  0.353788 -0.052812   
2   1.383970 -1.317822  0.123975  0.043758 -0.134047  0.088680  0.136664   
3  -0.285577 -0.956465 -0.070795  0.126882 -0.339024  0.431682 -0.036466   
4   0.505887 -0.772248 -0.196128 -0.698482 -0.977952  0.291180 -0.058590   
5   0.139040 -1.022992  0.222662 -0.820219 -0.403342  0.502229  0.043780   
6  -1.125896 -0.699048 -0.411038 -1.049683 -0.963801  0.112087 -0.111715   
7   0.804139 -0.926409 -0.021752 -0.530349 -1.049957 -1.744346 -0.208293   
8  -0.682317 -0.235497  0.245066  2.008464  0.343213 -2.057680  0.009135   
9  -0.665714  0.236016 -0.115199 -0.065868 -0.299639 -1.338271  0.045442   
10 -0.495503  0.862675  0.324341  0.454615  0.481537 -0.123256  0.068876   
11  1.045096 -0.947156  0.468234  0.828913  0.958826  0.084605 -0.055913   
12  0.514910 -0.633485  0.348839  0.893543 -0.409540 -0.339176  0.231314   
13 -0.217590 -0.260587  0.480708 -0.369192 -0.261390  0.416872 -0.010705   
14  0.418795 -1.719195  0.645626  0.233274 -0.030954  0.112246  0.074086   
15 -0.655393 -0.404798  0.039023  0.119391 -0.641459 -0.134895  0.163801   
16 -0.007632 -1.168786 -0.354808  0.796618 -0.411340  0.520898 -0.008246   
17  0.397568 -1.495616  0.427256  0.929493 -0.921097  0.269159  0.030016   
18 -0.257103 -0.517592 -0.047676  1.208477 -0.124120  0.436017 -0.009999   

         f_7       f_8       f_9      f_10      f_11      f_12      f_13  \
0   0.696373  0.204197 -0.640538 -1.268777 -0.502997  0.463260 -1.330727   
1   1.454771  0.345548 -0.522970 -0.090074  1.126331 -0.357611 -1.137713   
2   0.328222  0.521857  0.281087 -0.659636 -0.707708 -0.419449 -0.507346   
3   1.844441  0.592229 -0.500280 -0.829114  0.744380 -0.841767 -1.671612   
4   2.112324  0.451552 -0.903070 -0.721684  0.635161 -0.652323 -0.708185   
5   0.443958  0.250788 -0.441662 -0.966644  0.416846 -0.335546 -0.534507   
6   1.445988  0.255013 -0.598836 -0.871914  0.562513 -0.172921 -0.737253   
7   2.299100  0.846013 -1.233939 -1.159164  1.340370 -0.346796 -1.132954   
8   0.438135  1.079477  0.778933 -0.225972 -0.029768 -0.047482 -2.584598   
9   0.786776  0.575027 -0.188427 -0.406317 -0.027128 -0.453692 -1.158913   
10  1.088613 -0.370118 -0.622589 -0.972481 -0.138049  0.176741 -1.100818   
11  0.650364  0.092480 -0.171037 -1.288269  0.214831  0.346466 -0.624445   
12 -0.072762  0.786842  0.552776 -0.352649 -0.499139 -0.468411 -1.530816   
13  1.154040 -0.429741 -0.331582 -1.060740  0.016367  0.009960 -0.065271   
14  2.150335  0.568516 -0.499903 -2.048509  0.150464 -0.682668 -2.423329   
15  0.622690  0.864650  0.124070 -0.267612  0.261542 -1.024135 -1.895585   
16  1.437170  0.759766 -0.497068 -1.196831  0.315475 -0.608466 -1.383337   
17  1.531800  0.972211 -0.105255 -1.069748  0.914471 -1.078133 -1.917575   
18  0.580722  1.018441  0.121967  0.612558  1.227803 -1.453968 -1.869009   

        f_14  
0  -0.447457  
1   0.127587  
2   0.279108  
3   0.685388  
4   0.315887  
5   0.266648  
6   0.569262  
7  -1.021399  
8   0.428047  
9  -0.142867  
10  0.488087  
11 -0.601672  
12  0.829322  
13  0.475074  
14  0.986267  
15  0.958691  
16  0.316042  
17  0.643592  
18  0.639531

In [77]:
scipy.spatial.distance.cdist(df[df.prediction == 0].iloc[:, 1:], df[df.prediction != 0].iloc[:, 1:])

array([[4.50298326, 5.16024734, 7.1706936 , ..., 6.23435555, 6.03986704,
        6.80321443],
       [3.29288977, 3.95184078, 6.43708663, ..., 5.16825525, 5.38491082,
        6.32770647],
       [3.98903134, 4.36552961, 6.26626256, ..., 5.57628123, 5.17782428,
        6.88925439],
       ...,
       [3.97165818, 4.70412881, 6.82804352, ..., 6.25411332, 6.16011621,
        7.62098327],
       [4.65992563, 5.08749189, 7.2356132 , ..., 7.13319684, 7.07766171,
        8.36322648],
       [4.28727779, 4.03598665, 6.19221108, ..., 6.25226138, 6.36250308,
        7.00041406]])

In [68]:
df.prediction.unique()

array([5, 4, 8, 7, 6, 1, 0, 3, 2])

In [73]:
for fl in files:
    df = pandas.read_csv(fl, sep="\t", nrows=1000)
    for i in df["prediction"].unique():
        sub  = df[df.prediction == i]
        out = fl + "cluster_" + str(i) + ".tsv"
        if not pathlib.Path(out).exists():
            print("new")
            sub.to_csv(out, sep="\t", header=True, index=False)
        else:
            print("old")
            sub.to_csv(out, sep="\t", mode="a", header=False, index=False)

old
old
old
old
old
old
old
old
old


In [16]:
for f in files:
    df = return pandas.read_csv(fl, sep="\t", nrows=1000,
                           usecols=lambda x: x.startswith("f_"))

[]